[workspace]
members = [
  "apps/cli",
  "lib/syntax",
  "lib/parser",
  "lib/compile",
  "lib/uniquify",
  "lib/remove_complex_operands",
  "lib/explicate_control",
  "lib/select_instructions",
  "lib/assign_homes",
  "lib/patch_instructions",
  "lib/generate_prelude_conclusion",
  "tests"
]

resolver="2"
default-members=["apps/cli"]
