[workspace]
members = [
  "apps/cli",
  "lib/test_utils",
  "lib/syntax",
  "lib/parser",
  "lib/compile",
  "lib/uniquify",
  "lib/remove_complex_operands",
  "lib/explicate_control",
  "lib/select_instructions",
  "lib/uncover_live",
  "lib/interference_graph",
  "lib/color_graph",
  "lib/assign_homes",
  "lib/patch_instructions",
  "lib/generate_prelude_conclusion",
  "tests"
]

resolver="2"
default-members=["apps/cli"]
