[package]
name = "testsuite"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "testsuite"
path = "src/main.rs"

[dependencies]
driver = {path="../driver"}
chapter1 = {path="../chapter1"}
chapter2 = {path="../chapter2"}
chapter3 = {path="../chapter3"}
chapter4 = {path="../chapter4"}
